// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFBX2PChmI6W20293o3ncUlraDkx8G0Zw',
    appId: '1:810544075227:web:3e8a8da0215883a02a17fe',
    messagingSenderId: '810544075227',
    projectId: 'thimar-42cbb',
    authDomain: 'thimar-42cbb.firebaseapp.com',
    storageBucket: 'thimar-42cbb.appspot.com',
    measurementId: 'G-1ES362YG09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1EwAH71FLx3TJi3HZ-S4wFfkXlv6usA',
    appId: '1:810544075227:android:b639396930e1e5a42a17fe',
    messagingSenderId: '810544075227',
    projectId: 'thimar-42cbb',
    storageBucket: 'thimar-42cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBej69ixpuJ6NP0_TZuFvOHYoWk5Jyk5y4',
    appId: '1:810544075227:ios:2ac6e41536bb8ae22a17fe',
    messagingSenderId: '810544075227',
    projectId: 'thimar-42cbb',
    storageBucket: 'thimar-42cbb.appspot.com',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBej69ixpuJ6NP0_TZuFvOHYoWk5Jyk5y4',
    appId: '1:810544075227:ios:2ac6e41536bb8ae22a17fe',
    messagingSenderId: '810544075227',
    projectId: 'thimar-42cbb',
    storageBucket: 'thimar-42cbb.appspot.com',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFBX2PChmI6W20293o3ncUlraDkx8G0Zw',
    appId: '1:810544075227:web:f50b5abbdf31fd312a17fe',
    messagingSenderId: '810544075227',
    projectId: 'thimar-42cbb',
    authDomain: 'thimar-42cbb.firebaseapp.com',
    storageBucket: 'thimar-42cbb.appspot.com',
    measurementId: 'G-RP5J8W41WK',
  );
}
